version: "3.8"
services:
  database:
    container_name: postgres
    build: 
      context: ./docker
      dockerfile: Dockerfile.db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
