# Generated by Django 4.1.13 on 2024-08-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ec2_starter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ec2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=20, unique=True)),
                ('region', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('last_start_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
