# Generated by Django 4.1.13 on 2024-08-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec2_starter', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
