# Generated by Django 5.1.2 on 2026-04-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec2_starter', '0004_remove_unused_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ec2',
            options={'verbose_name': 'EC2 Instance', 'verbose_name_plural': 'EC2 Instances'},
        ),
    ]
